bugst/go-serial

serial_darwin.go
serial_darwin_386.go
serial_darwin_amd64.go
serial_freebsd.go
serial_linux.go
serial_unix.go

This should disable RTS/CTS flow control.
The constant `syscall.CRTSCTS` is not defined in golang, so I had to do a bit of research to find its value for all unix flavors.
Hopefully this fix #3, @jcw may you test it? you should need to patch only `serial_darwin.go` and `serial_unix.go` to try.

Disable RTS/CTS handshake by default

---

serial.go
serial_darwin.go
serial_darwin_386.go
serial_darwin_amd64.go
serial_freebsd.go
serial_linux.go
serial_unix.go

This PR removes the `termiosMask(..)`  function and use the correct type for bitmasks for each OS/ARCH. This change requires a bit of copying in darwin 386/amd64 but simplifies the overall design.
I've added some other commits that improves error handling if invalid settings are passed when changing serial port mode.

Slightly improved bitmasks for posix

---

enumerator/enumerator.go

It pointing to mksyscal_windows.go in local folder which already removed

Enumerator: Fixed go:generate comment

---

.travis.yml
enumerator/usb_darwin.go

go1.10.4 and go1.11 introduced a change in how `C.CFDictionaryRef` are mapped from C lang to go land.
https://github.com/arduino/arduino-cli/issues/13

Fix osx build (again...)

---

serial_unix.go

This has been observed in particular on MacOS, in this case just retry the call without throwing the error back to the user.
Related to:
https://github.com/arduino/arduino-cli/issues/504
https://github.com/arduino/arduino-pro-ide/issues/157
@kittaakos

Transparently handle EINTR during Read

---

serial_windows.go

Hello,
Thank you for creating this awesome library! We have found a problem where on machine without serial ports the library returns error `ErrorEnumeratingPorts`. We found it in VirtualBox machine. Issue occurs because the registry key `HARDWARE\DEVICEMAP\SERIALCOMM\` does not even exist. It seems a valid case to us and we think it should return empty slice instead of an error.
Please feel free to comment if the code is not up to your standards we would fix it.
Thank you.

Fixing getPortList on windows without any ports

---

serial_darwin_64.go

Support arm64 which is used by the new lineup of computers
from apple.
Fixes #97

add support for darwin arm64

---

go.mod
go.sum

This updates the goselect dependency to support riscv

update goselect to get riscv support

---

serial.go

Replace old mkwinsyscall call by the new version which is recommended
by Go since version 1.13.3.
Based on https://github.com/golang/go/blob/go1.13.3/src/syscall/mksyscall_windows.go

update go generate

---

enumerator/usb_darwin.go

Seems like, starting from 10.11, `IOUSBDevice` has been renamed to `IOUSBHostDevice`.

Added support for macosx 10.11+

---

enumerator/syscall_windows.go
enumerator/usb_windows.go

On composite USB devices the serial number is usually reported on the parent device object.

Windows improve usb serial number discovery

---

serial.go
serial_unix.go
serial_windows.go

Supersedes #82 
Supersedes #33 
Fix #48 
Related to #105

Implementation of read timeouts

---

go.mod
go.sum

For some strange reason the interaction between the go-sqlite3 lib and the go-serial produced a weird panic as described in:
https://github.com/bugst/go-serial/issues/115
https://github.com/bugst/go-serial/issues/116
The solution is to just upgrade the x/unix package to the latest version available at the moment.
Fix #115
Fix #116
/cc @huyungtang @002269

Fixed runtime build problem with darwin/amd64

---

serial_linux.go

i.MX-based serial controllers are detected as /dev/ttymxc

Added detection of UART ports (/dev/ttymxc*)

---

serial_unix.go

A very small port.readTimeout may lead to a negative timeout if the elapsed time between:
deadline = time.Now().Add(port.readTimeout)
and
timeout = time.Until(deadline)
is longer than port.readTimeout.
Fix #134

Fix potential small timeout bug on unix implementation

---

serial.go
serial_unix.go
serial_windows.go

Based on #47, the API is slightly different to allow `DTR` and `RTS` to default to `true` if not specified:
```
port, err := serial.Open("/dev/ttyUSB0", &serial.Mode{BaudRate: 9600})
```
this is the full initialization:
```
port, err := serial.Open("/dev/ttyUSB0", &serial.Mode{
BaudRate: 9600,
DataBits: 8,
Parity:   serial.NoParity,
StopBits: serial.OneStopBit,
InitialStatusBits: &serial.ModemOutputBits{
RTS: true,
DTR: false,
},
})
```

Allow setting RTS and DTR on `Open`

---

serial_windows.go

Build on top of #144 (thanks @palazzol).
I've taken the commit from #144 and removed also the timeout logic that is no more needed.

Remove unnecessary code, originally for checking for disconnects when using non-overlapped I/O

---

enumerator/usb_windows.go

windows: Avoid panic if USB Product name is empty

---

serial_linux.go
serial_unix.go

Add ttyHS support for linux.
Tested with `example_getportlist_test` on Linux ARM64, Linux AMD64 and Windows.
Linux can get ttyHSxxx and ttySxxx, Windows can get COMx.

feat: add ttyHS support for linux

---

serial.go
serial_bsd.go
serial_linux.go
serial_windows.go

Tested on Mac OS, Linux and Windows with UART emulated on USB.
I wrote general BSD code, because it should work, but I am not able to test it.
On Mac OS I am quite sure that drain behaves as needed.
For Windows it seems that drain is actually part of `Write`, because `Write` was slow and `Drain` was fast. But I have not found any mention in Win32 docs about buffering and asynchronous write, so I kept it.
For Linux `Drain` is also taking more time than writing.

add support for drain

---

enumerator/usb_darwin.go

This is needed starting with Go 1.21 due to stricter enforcement of rules about adding methods to existing types, now including C types. It should fix #162 
See https://github.com/golang/go/issues/60725 for further details.

darwin: use Go type wrappers to avoid declaring Go methods on C types.

---

enumerator/usb_darwin.go

We had reports of users always getting:
```
IOServiceGetMatchingServices failed, data changed while iterating
```
The issue seems related to the function getMatchingServices which returns an always-invalid iterator even if there are no actual services.
This is a workaround for this issue.

Fix some rare MacOSX USB port enumerator failures

---

serial_unix.go

I noticed there were a few cases where `nativeOpen()` would return an error but wouldn't explicitly close the port, I've fixed those cases.

unix: nativeOpen: always close the port on errors

---

serial_unix.go

It should allow a better debugging of errors during port initialization on Unix-based systems.

Improved error messages

---

enumerator/usb_wasm.go
enumerator_wasm.go
serial_wasm.go

Fixes build errors:
GOOS=js GOARCH=wasm go build
GOOS=wasip1 GOARCH=wasm go build

fix: add shims for GOARCH=wasm with GOOS=js and GOOS=wasip1

---

.github/workflows/test.yaml

Also enable explicit ARM64 builds.
This fixes the issue with `Error: enumerator/enumerator.go:31:9: undefined: nativeGetDetailedPortsLis` on MacOS/Darwin builds

Workflows: Use CGO_ENABLED=1 for MacOS

---

.github/workflows/test.yaml

This PR bumps GitHub workflow actions to latest versions, thus avoiding deprecation warnings, as e.g. seen [here](https://github.com/bugst/go-serial/actions/runs/8237610031).

Bump GitHub workflow actions to latest versions

---

portlist/portlist.go

When [checking](https://goreportcard.com/report/go.bug.st/serial) the project with Go Report card service there is a warning that the code is not 100% formatted to Go standard. This PR fixes this issue.

Go-format source code: fix warning

---

serial_windows.go

It seems that the CH340 driver does not correctly support the `SetCommTimeouts` system call.
In particular calling `SetCommTimeouts` with the following settings
```
Windows.CommTimeouts{
ReadIntervalTimeout:         0xFFFFFFFF,
ReadTotalTimeoutMultiplier:  0xFFFFFFFF,
ReadTotalTimeoutConstant:    0xFFFFFFFE,
}
```
should set timeout to infinity and block the `Read` call until at least one byte is received. In reality, the CH340 behaves like there is no timeout, returning the available data immediately (or an empty read if there is no data). This violates the [`SetCommTimeout` definition](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setcommtimeouts), while all the other drivers [correctly honor the timeout](https://learn.microsoft.com/en-us/windows/win32/api/winbas …

Hack to workaround misbehaving CH340 drivers on Windows

---

serial_windows.go

v1.6.3 breaks serial port enumeration by reading registry value names instead of registry values as it was in <=v1.6.2.
This results in `GetPortsList()` function returning `\\Device\\USBSER001`, etc. instead of `COMXX`.
This pull request fixes `nativeGetPortsList` to read the actual values, which is consistent with previous versions.
It also modifies `nativeOpen` to check for if the port name has `\\.\` prefix, which was previously added unconditionally, which caused open to fail if the port name already had that prefix.

Port enumeration on Windows

---

serial_windows.go

Fixes #204.
Bring back constants from #187 and revert the code in `GetModemStatusBits` to fix data gathering.
Ideally, this enum should get added to `golang.org/x/sys/windows` as @twpayne did for other constants.

fix: incorrect masks for modem status bits on Windows
